local assert = dofile(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h') .. '/helpers/assert.lua')

describe('integrations.git', function()
    it('parses shortstat output', function()
        local parser = require('luxline.integrations.git.parser')
        assert.eq(parser.parse_diff_stats('3 files changed, 10 insertions(+), 2 deletions(-)'), '~3 +10 -2')
        assert.eq(parser.parse_diff_stats('1 file changed, 1 insertion(+)'), '~1 +1')
        assert.eq(parser.parse_diff_stats('2 files changed, 4 deletions(-)'), '~2 -4')
        assert.eq(parser.parse_diff_stats(''), '')
        assert.eq(parser.parse_diff_stats(nil), '')
    end)

    it('defines each cache key exactly once', function()
        local git_cache = require('luxline.integrations.git.cache')
        assert.eq(git_cache.keys.branch('/repo'), 'branch_/repo')
        assert.eq(git_cache.keys.diff('/repo'), 'diff_/repo')
        assert.eq(git_cache.keys.repo_root('/path'), 'repo_root_/path')
    end)

    it('clear_cache resets per-repo state and cache entries', function()
        local git_cache = require('luxline.integrations.git.cache')
        local state = require('luxline.core.state')
        state.set_git_info('/repo', { branch = 'main', diff = '~1 +1' })
        git_cache.clear_cache('/repo')
        assert.eq(state.get_git_info('/repo'), { branch = '', diff = '' })
    end)

    it('resolves this repository root and reads branch/diff state', function()
        local git = require('luxline.integrations.git')
        require('luxline.config').setup({})
        local root = git.get_repo_root_cached(vim.fn.getcwd())
        assert.truthy(root, 'plan runs inside the nvim-luxline repo')
        assert.eq(git.is_git_repo, nil, 'dead is_git_repo removed from the facade')
        assert.eq(require('luxline.integrations.git.commands').is_git_repo, nil, 'and from commands')
        assert.eq(type(git.get_branch(root)), 'string')
        assert.eq(type(git.get_combined(root)), 'string')
    end)
end)
