local assert = dofile(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h') .. '/helpers/assert.lua')

describe('concrete items', function()
    it('renders every built-in item against a scratch buffer', function()
        require('luxline').setup({ git_enabled = false })
        local buf = vim.api.nvim_create_buf(false, false)
        vim.api.nvim_set_current_buf(buf)
        vim.api.nvim_set_option_value('filetype', 'lua', { buf = buf })
        local ctx = require('luxline.core.context').get_current_context()
        local items = require('luxline.items')

        assert.eq(items.get_value('filetype', nil, ctx), 'lua')
        assert.eq(items.get_value('filename', nil, ctx), '[No Name]')
        assert.eq(items.get_value('spacer', nil, ctx), '%=')
        assert.matches('^%d+$', items.get_value('windownumber', nil, ctx))
        assert.matches('^%d+:%d+$', items.get_value('position', nil, ctx))
        assert.matches('^%d+$', items.get_value('position', 'line', ctx))
        assert.eq(items.get_value('modified', nil, ctx), '')
        vim.api.nvim_set_option_value('modified', true, { buf = buf })
        assert.eq(items.get_value('modified', 'short', ctx), '[+]')
        assert.eq(items.get_value('readonly', nil, ctx), '')
        assert.eq(items.get_value('encoding', 'short', ctx), 'UTF8')
        assert.truthy(items.get_value('cwd', nil, ctx) ~= '')
    end)

    it('git item returns empty outside a repo and the registry drops the async flag', function()
        require('luxline').setup({ git_enabled = false })
        local items = require('luxline.items')
        assert.eq(items.get_value('git', 'status', { bufnr = 0, cwd = '/' }), '')
        local info = items.get_item_info('git')
        assert.eq(info.async, nil, 'async flag is removed from registry metadata')
        assert.eq(info.variants, { 'branch', 'combined', 'diff', 'status' })
    end)

    it('auto-discovers all eight item modules on setup', function()
        local items = require('luxline.items')
        local count = items.auto_discover()
        assert.eq(count, 8, 'file, git, modified, position, readonly, encoding, windownumber, spacer')
    end)

    it('keeps get_items_by_category removed', function()
        assert.eq(require('luxline.items').get_items_by_category, nil)
    end)
end)
