local assert = dofile(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h') .. '/helpers/assert.lua')
local color = require('luxline.primitives.color')

describe('primitives.color', function()
    it('parses and formats round-trip', function()
        assert.eq(color.parse('#1a2b3c'), { r = 0x1a, g = 0x2b, b = 0x3c })
        assert.eq(color.format({ r = 0x1a, g = 0x2b, b = 0x3c }), '#1a2b3c')
        assert.eq(color.parse('not-a-color'), nil)
        assert.eq(color.parse('#12345'), nil)
    end)

    it('validates hex strings with an anchored pattern', function()
        assert.truthy(color.is_hex('#aabbcc'))
        assert.falsy(color.is_hex('#aabbccdd'))
        assert.falsy(color.is_hex('aabbcc'))
        assert.falsy(color.is_hex(123456))
    end)

    it('adjusts with channel clamping', function()
        assert.eq(color.adjust('#000000', 16), '#101010')
        assert.eq(color.adjust('#fafafa', 16), '#ffffff')
        assert.eq(color.adjust('#101010', -32), '#000000')
        assert.eq(color.adjust('nonsense', 16), 'nonsense')
    end)

    it('interpolates linearly with rounding, matching the legacy themes implementation', function()
        local steps = color.interpolate('#000000', '#0000ff', 7)
        assert.eq(#steps, 7)
        assert.eq(steps[1], '#000000')
        assert.eq(steps[7], '#0000ff')
        assert.eq(steps[4], '#000080')
    end)

    it('reads resolved highlight colors as #-prefixed hex or nil', function()
        vim.api.nvim_set_hl(0, 'LuxColorSpecA', { fg = '#112233', bg = '#445566' })
        vim.api.nvim_set_hl(0, 'LuxColorSpecLink', { link = 'LuxColorSpecA' })
        assert.eq(color.from_highlight('LuxColorSpecA'), { fg = '#112233', bg = '#445566' })
        assert.eq(color.from_highlight('LuxColorSpecLink'), { fg = '#112233', bg = '#445566' })
        local empty = color.from_highlight('LuxColorSpecMissing')
        assert.eq(empty.bg, nil)
        assert.eq(empty.fg, nil)
    end)
end)
