local assert = dofile(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h') .. '/helpers/assert.lua')
local cache = require('luxline.primitives.cache')

describe('primitives.cache', function()
    it('stores and retrieves within a namespace', function()
        local ns = cache.namespace('spec_a')
        ns:set('key', 'value')
        assert.eq(ns:get('key'), 'value')
        assert.eq(cache.namespace('spec_a'):get('key'), 'value', 'same handle for same name')
    end)

    it('isolates namespaces', function()
        cache.namespace('spec_b'):set('key', 'b')
        cache.namespace('spec_c'):set('key', 'c')
        assert.eq(cache.namespace('spec_b'):get('key'), 'b')
        assert.eq(cache.namespace('spec_c'):get('key'), 'c')
    end)

    it('expires entries after their ttl', function()
        local ns = cache.namespace('spec_ttl')
        ns:set('key', 'value', 20)
        assert.eq(ns:get('key'), 'value')
        vim.wait(80, function() return false end)
        assert.eq(ns:get('key'), nil)
    end)

    it('clears one key, the whole namespace, and everything', function()
        local ns = cache.namespace('spec_clear')
        ns:set('k1', 1)
        ns:set('k2', 2)
        ns:clear('k1')
        assert.eq(ns:get('k1'), nil)
        assert.eq(ns:get('k2'), 2)
        ns:clear()
        assert.eq(ns:get('k2'), nil)
        ns:set('k3', 3)
        cache.clear_all()
        assert.eq(ns:get('k3'), nil)
    end)
end)
