local assert = dofile(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h') .. '/helpers/assert.lua')

describe('public surface', function()
    it('keeps the README-documented API', function()
        local luxline = require('luxline')
        assert.truthy(luxline.setup)
        assert.truthy(luxline.reload)
        assert.truthy(luxline.reset)
        assert.truthy(luxline.get_stats)
        assert.truthy(luxline.update)
        assert.truthy(luxline.throttled_update)
        assert.truthy(luxline.set_theme)
        assert.truthy(luxline.get_theme)
        assert.truthy(luxline.get_theme_names)
        assert.truthy(luxline.create_gradient_theme)
        assert.truthy(luxline.debug)
        assert.truthy(luxline.preview_config)
        assert.truthy(luxline.config)
        assert.eq(luxline._VERSION, '3.0.0')
    end)

    it('removes the undocumented surface', function()
        local luxline = require('luxline')
        assert.eq(luxline.bar_builder, nil)
        assert.eq(luxline.items, nil)
        assert.eq(luxline.highlight, nil)
        assert.eq(luxline.highlight_strategies, nil)
        assert.eq(luxline.validate_config, nil)
        assert.eq(luxline.get_config_schema, nil)
        assert.eq(luxline.create_item, nil)
        assert.eq(luxline.create_theme, nil)
    end)

    it('setup + get_stats round-trips', function()
        local luxline = require('luxline')
        luxline.setup({ git_enabled = false })
        local stats = luxline.get_stats()
        assert.eq(stats.initialized, true)
        assert.truthy(stats.items_count >= 10)
    end)
end)
